import turtle

turtle.shape("turtle")
turtle.color("black","yellow")
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()    
turtle.up() 
turtle.setpos(-30,100)
turtle.down()
turtle.color("black","blue")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

turtle.up() 
turtle.setpos(30,100)
turtle.down()
turtle.color("black","blue")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

turtle.up() 
turtle.setpos(0,90)
turtle.down()
turtle.right(90)
turtle.forward(20)

turtle.up() 
turtle.setpos(-60,80)
turtle.down()
turtle.pensize(10)
turtle.color("red","red")
turtle.circle(60,180)

